spring:
  application:
    name: qa_live_test

http:
  placeholder-api:
    url: https://jsonplaceholder.typicode.com

playwright:
  ws-endpoint: ws://localhost:3002
  timeout: 8s
  url: http://localhost:3000