services:
  app:
    container_name: qa_live_test_app
    image: janisnarbuts/qa_live_test_app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9998:8080"

  db:
    container_name: qa_live_test_app_db
    image: postgres:15.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "9999:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
