services:
  app-backend:
    container_name: qa_live_test_app_backend
    image: janisnarbuts/qa_live_test_app:latest-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9998:8080"

  app-frontend:
    container_name: qa_live_test_app_frontend
    image: janisnarbuts/qa_live_test_app:latest-frontend
    environment:
      API_BASE_URL: http://localhost:9998/api/users
    depends_on:
      - app-backend
    ports:
      - "9997:80"

  db:
    container_name: qa_live_test_app_db
    image: postgres:15.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "9999:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 2s
      retries: 10
